# sync-prompts.ps1
# Syncs the content of a source markdown file to multiple target markdown files.
# It handles both the original Korean files and the translated English (.en.md) files.
#
# Usage: powershell -ExecutionPolicy Bypass -File scripts/sync-prompts.ps1

# --- Configuration ---
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir
$nl = [Environment]::NewLine

# Sync configuration for different language sets
$syncConfigs = @(
    @{
        Source = "CLAUDE.md"
        Targets = @("GEMINI.md", "AGENTS.md", ".github/copilot-instructions.md")
        Header = "<!-- AUTO-GENERATED: Do not edit this file directly. Edit CLAUDE.md and run scripts/sync-prompts.ps1 -->"
    },
    @{
        Source = "CLAUDE.en.md"
        Targets = @("GEMINI.en.md", "AGENTS.en.md")
        Header = "<!-- AUTO-GENERATED: Do not edit this file directly. Edit CLAUDE.en.md and run scripts/sync-prompts.ps1 -->"
    }
)

# --- Execution ---
foreach ($config in $syncConfigs) {
    $sourcePath = Join-Path $projectRoot $config.Source
    
    if (-not (Test-Path $sourcePath)) {
        Write-Warning "Source file not found, skipping: $sourcePath"
        continue
    }

    Write-Host "Processing source: $($config.Source)"
    
    $content = Get-Content $sourcePath -Raw -Encoding UTF8
    $headerContent = $config.Header + $nl + $nl
    $output = $headerContent + $content

    foreach ($targetFile in $config.Targets) {
        $targetPath = Join-Path $projectRoot $targetFile
        $targetDir = Split-Path -Parent $targetPath
        if (-not (Test-Path $targetDir)) {
            New-Item -ItemType Directory -Force $targetDir | Out-Null
        }
        try {
            [System.IO.File]::WriteAllText($targetPath, $output, [System.Text.UTF8Encoding]::new($false))
            Write-Host "  -> Synced to $targetFile"
        }
        catch {
            Write-Error "Failed to write to target file: $targetPath. Error: $_"
        }
    }
    Write-Host ""
}

Write-Host "Done. All prompt files are in sync."

